# Generated by Django 4.1.7 on 2023-03-27 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Usu_ite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('fecha_update', models.DateTimeField(auto_now=True)),
                ('fecha_create', models.DateTimeField(auto_now_add=True)),
                ('dif_fecha', models.DurationField()),
                ('id_itinerario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey_app.itinerario')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
                ('itin_usuario', models.ManyToManyField(through='journey_app.Usu_ite', to='journey_app.itinerario')),
            ],
        ),
        migrations.AddField(
            model_name='usu_ite',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journey_app.usuario'),
        ),
    ]
