# Generated by Django 4.1.7 on 2023-03-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey_app', '0002_alter_usuario_options_remove_usuario_itin_usuario_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usu_ite',
            options={'verbose_name': 'Usu_ite', 'verbose_name_plural': 'Usu_iten'},
        ),
        migrations.RenameField(
            model_name='usu_ite',
            old_name='id_itinerario',
            new_name='itinerario',
        ),
        migrations.RenameField(
            model_name='usu_ite',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='usu_ite',
            name='dif_fecha',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='usu_ite',
            name='fecha_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
