# Generated by Django 4.1.7 on 2023-04-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey_app', '0004_alter_usu_ite_dif_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
