# Generated by Django 4.1.7 on 2023-04-11 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journey_app', '0005_usuario_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usu_ite',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usu_ites', to='journey_app.usuario'),
        ),
    ]
