# Generated by Django 4.1.7 on 2023-04-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journey_app', '0006_alter_usu_ite_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('id_pregunta', models.IntegerField()),
                ('id_respuesta', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Encuestas',
            },
        ),
    ]
